### ISSUE TITLE
Installation commands error: can't open file 'pip': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by javiroman** [keedio/kafka-hue#11]
The command:

$ sudo -E -u hue .$HUE_HOME/build/env/bin/python pip install zope.interface

Fails with "error: can't open file 'pip': [Errno 2] No such file or directory".

You can fix this with something like:

$ sudo -E -u hue .$HUE_HOME/build/env/bin/python $HUE_HOME/build/env/bin/pip install zope.interface

**Comment by sag7777** [comment]
DEBUG:validate_email:ServerError or socket.error exception raised (timed out)
need the solution for this error
