### ISSUE TITLE
Include name of Ganglia Cluster in Hue.ini

### ISSUE THREAD

**Issue by jjmleiro** [keedio/kafka-hue#38]
Add to Hue.ini, name of Ganglia Cluster.

**Comment by danieltardon** [comment]
In views.py line 325 (Development branch):

aURL = aURL + [cluster['ganglia_server'] + "/ganglia/graph.php?" + "r=" + sGranularity + "&c=GangliaCluster&h=" + sHost + "&m=" + metric + "&" + metric + "&json=1"]                

c=GangliaCluster must be a configurable variable in hue.ini
